### ISSUE TITLE
Get rid of console error

### ISSUE THREAD

**Issue by rafelafrance** [MapofLife/datasets#18]
Get rid of "angular.js:13708 TypeError: Cannot read property 'controls' of undefined" console error

**Comment by funkycoda** [comment]
Would Google Maps help instead of Leaflet?

**Comment by funkycoda** [comment]
@rafelafrance is working on the [Google Maps version](https://github.com/MapofLife/datasets/tree/google-maps) which _may_ help with fixing this and other map related issues.

**Comment by jmalczyk** [comment]
Might work, but may just replace the problem with a new one. When the
angular-google-maps directive is swapped in an out of templates I have had
issues getting the "resize" map event to fire, which leads to tiles
dropping off the right and bottom side. That may not be an issue here
because the size of the map is fixed (vs in flexbox).

We would like to use Google Maps for everything though, so even if this
does not totally address the problem it is not wasted effort.

**Comment by rafelafrance** [comment]
I can confirm that resize is a problem here too.

**Comment by funkycoda** [comment]
Agreed, might fix some issues, but the "resize" problem might exist when showing/hiding the map too. Just another thing to watch out for.

**Comment by jmalczyk** [comment]
Check out this issue for a potential fix

https://github.com/angular-ui/angular-google-maps/issues/1114

There is a ui-router-extras module that lets you make a state "sticky" so
the directive never gets destroyed, that sounds like it might do it for us
(for gmaps and leaflet).

http://christopherthielen.github.io/ui-router-extras/#/sticky

**Comment by jmalczyk** [comment]
Looks like we are mostly past this? The remaining errors are likely ui-leaflet internal, possibly related UTF grid $http promises resolving after their tiles have dropped out of DOM (that's my WAG anyway).

**Comment by funkycoda** [comment]
This looks like it's working now. 

Do we (eventually?) want to move to Google Maps anyways, @jmalczyk?

**Comment by jmalczyk** [comment]
Let's stick with Leaflet for now.
