### ISSUE TITLE
Zoom to dataset bounds or geographic scope

### ISSUE THREAD

**Issue by funkycoda** [MapofLife/datasets#6]
When viewing a dataset info, the map should automatically zoom to the its bounds. For instances where there isn't a map associated (there should be one for all datasets?), we should zoom to the geographic scope, where available.

Example dataset:  http://mol.org/datasets/eb6963c6-694e-4135-be03-8aa88d5dd913

@ljvillanueva, can you comment why there are no maps associated with some of the datasets?

**Comment by villanueval** [comment]
Some datasets dont have the geohashes yet. They are in prep.

**Comment by jmalczyk** [comment]
Everythign should have geohashes now, and the maps are zooming the the visible extent of the selection. http://mol.org/datasets/269074a8-8a8b-4ad4-9896-6639085a3207. They are a bit slower because of that because there is an extra api call internally. We may be able to split those up to speed things along.
